project:
  type: book

book:
  title: "Random Forest in Economic Panel Data Analysis: Fundamentals and Methodology"
  author: "Mart√≠n Gabriel Cargnel"
  date: last-modified
  date-format: "MMM, YYYY"
  chapters:
    - index.qmd
    - sections/1_intro.qmd
    - sections/2_related_work.qmd
    - sections/3_panel_data.qmd
    - sections/references.qmd


bibliography: references.bib
csl: apa-6th-edition.csl
link-citations: true
lang: en
execute:
  echo: false
  include: false
  fig-align: center
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc-depth: 2