project:
  type: book

book:
  title: "Double Machine Learning for Difference in Difference: Fundamentals and Application"
  author: "Mart√≠n Gabriel Cargnel"
  date: last-modified
  date-format: "MMM, YYYY"
  chapters:
    - index.qmd
    - sections/1_intro.qmd
    - sections/2_did.qmd
    - sections/3_dml.qmd
    - sections/4_application.qmd
    - sections/references.qmd


bibliography: references.bib
csl: apa-6th-edition.csl
link-citations: true
lang: en
execute:
  echo: false
  include: false
  fig-align: center
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc-depth: 2